pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('List Files') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker --version'
            }
        }

        stage('Finished') {
            steps {
                echo 'Pipeline executed successfully!'
            }
        }
    }
}